### ISSUE TITLE
Byte Order Marker written to file after log event in certain circumstances

### ISSUE THREAD

**Issue by Jhaiii** [serilog/serilog-sinks-file#209] opened 2021-03-15 16:56 UTC
In FileSink.cs, EmitOrOverFlow:
`                _textFormatter.Format(logEvent, _output);
                if (!_buffered)
                    _output.Flush();`

The Format step is unbuffered and written direct to file, then the buffer is flushed (which writes the BOM).
This results in a corrupt log file (which is difficult to notice without inspecting the bytes.  This results in Elastic Logstash rejecting logs as it cannot handle the BOM chars in the wrong place.

Here is a powershell util to read the bytes to help with investigation:
`
$fs = [IO.File]::Open("C:\\blahblah\\Buffer-20210315.json", 
                  [IO.FileMode]::Open, 
                  [IO.FileAccess]::Read, 
                  [IO.FileShare]::ReadWrite)

$bytes = [byte[]]@()
while($fs.Position -lt $fs.Length)
{
    $a=$fs.ReadByte()
    $bytes += $a
}
[System.Text.Encoding]::ASCII.GetString($bytes)
$fs.Dispose()
`

(BOM shows as '???'

**Comment by cocowalla** [comment] 2021-03-15 18:01
Hi, thanks for the report! Are you saying a BOM is being written every single time `_output.Flush()` is called (that is, after every single log event when in unbuffered mode)?

**Comment by Jhaiii** [comment] 2021-03-15 20:46
It is only once.  The result is a BOM after the first log.  Subsequent logs are ok. This would be resolved by flushing the buffer when the file is first created I guess.

**Comment by cocowalla** [comment] 2021-03-15 22:30
Thanks for the extra info, I'll try to reproduce with a test

**Comment by cocowalla** [comment] 2021-03-16 13:04
I'm unable to reproduce this. I added this to `FileSinkTests` to play around and try to replicate the issue you describe:

```c#
public class FileSinkTests
{
    [Fact]
    public void Repro()
    {
        var encoding = Encoding.UTF8;
        var path = @"C:\Temp\serilog\out.txt";

        if (System.IO.File.Exists(path))
        {
            System.IO.File.Delete(path);
        }

        var evt = Some.LogEvent("Irrelevant as it will be replaced by the formatter");
        const string actualEventOutput = "x";
        var formatter = new FixedOutputFormatter(actualEventOutput);
        var eventOuputLength = encoding.GetByteCount(actualEventOutput);

        using (var sink = new FileSink(path, formatter, 1000000, encoding, buffered: false))
        {
            sink.Emit(evt);
            sink.Emit(evt);
            sink.Emit(evt);
        }

        var size = new FileInfo(path).Length;
        Assert.Equal(encoding.GetPreamble().Length + eventOuputLength * 3, size);
    }
}
```

The test passes, and I double-checked with a hex editor and confirmed that the BOM was only written once at the start of the file.

If I've misunderstood the conditions, would appreciate if you could set me right, or even better, provide a reproduction?

**Comment by Jhaiii** [comment] 2021-03-16 14:37
Firstly, thank you for looking into this so quickly.  Your test does not replicate the issue as your TextFormatter calls output.Write() which uses the buffer.  When I look at the Elastic EcsTExtFormatter [,](https://github.com/elastic/ecs-dotnet/blob/master/src/Elastic.CommonSchema.Serilog/EcsTextFormatter.cs) the write to the stream is done via serializer that doesn't appear to buffer, hence the out of order writing of BOM.  

`public virtual void Format(LogEvent logEvent, TextWriter output)
		{
			var ecsEvent = LogEventConverter.ConvertToEcs(logEvent, _configuration);
			if (output is StreamWriter sw)
			{
				ecsEvent.Serialize(sw.BaseStream);
				sw.WriteLine();
			}
			else
			{
				var bytes = ecsEvent.SerializeToUtf8Bytes();
				output.WriteLine(Encoding.UTF8.GetString(bytes));
			}
		}`


This may be more of an Elastic issue, but I guess there is a risk that different ITextFormatter implementations may result in the buffer not being used.

**Comment by cocowalla** [comment] 2021-03-16 16:06
Do you think you could try and produce a minimal working example that reproduced this issue?

**Comment by nblumhardt** [comment] 2021-03-16 21:56
Thanks for the report. The bug is in the `EcsTextFormatter` snippet you've posted above - writing directly to `BaseStream`, when handed a `TextWriter`, doesn't work reliably:

 * The `TextWriter` may be buffering (as you'd observed) - this could be fixed by the formatter flushing the writer first, but would be worse for performance than the alternative branch in their conditional, and
 * The `TextWriter` is responsible for defining an `Encoding` - skipping directly to the base stream and ignoring the encoding will produce corrupted results, if serilalization happens to use a different one.

Needs an issue in the `ecs-dotnet` repo, but happy to chime in/help wherever I can.

**Comment by Jhaiii** [comment] 2021-03-17 08:06
Thanks Both. Appreciate you working through this one with me.  I will raise an issue on ecs-dotnet.

**Closed** 2021-03-17 10:37 UTC

**Comment by Jhaiii** [comment] 2021-03-17 11:01
I created an [issue](https://github.com/elastic/ecs-dotnet/issues/131) on `ecs-dotnet`.  I won't close this just yet until those guys accept the issue.

**Comment by nblumhardt** [comment] 2021-03-17 11:09
Thanks for the link! We try to keep open issues to thinks we need to act on here. If it turns out there's something needed in this project, please just let us know and we'll reopen 👍
