### ISSUE TITLE
Rolling file naming

### ISSUE THREAD

**Issue by micktion** [serilog/serilog-sinks-file#249] opened 2022-02-28 06:38 UTC
Just wondering if there's options for someone coming from log4net such that the name of the most current rolling log file never changes?

i.e. the log file name being logged to is MyApp.log... when the log gets rolled, the existing file is closed and renamed using the rolling naming system.  

In log4net if you specified a maximum of 4 you would have ...

MyApp.log   <= always the latest
MyApp.log.1
MyApp.log.2
MyApp.log.3

The reason why this is a great feature is that you can just leave the MyApp.log file in a text editor and when it reloads you're looking at the latest that has been logged, rather than logging to a file named by the time the log was created, forcing you to close the previous days log file and open a file with a new name every day.

**Comment by bartelink** [comment] 2022-02-28 14:53
Duplicate of https://github.com/serilog/serilog-sinks-file/issues/40 - see  https://github.com/dfacto-lab/serilog-sinks-file for an impl of what you are after

**Closed** 2022-02-28 21:24 UTC
Labels: duplicate
