### ISSUE TITLE
Potential Xamarin Issue

### ISSUE THREAD

**Issue by CostaTC** [serilog/serilog-sinks-file#44] opened 2017-12-04 03:16 UTC
Hi there,

Found an odd issue when running the following code in Xamarin:

`Log.Logger = new LoggerConfiguration()
                .WriteTo.File(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Personal), "XamarinLib-{Date}.txt")
                , outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level}] [{SourceContext}] {Message}{NewLine}{Exception}",
                        fileSizeLimitBytes: 100000000,
                        rollingInterval: RollingInterval.Day,
                        rollOnFileSizeLimit: true,
                        shared: true,
                        retainedFileCountLimit: 31,
                        encoding: Encoding.UTF8)
                .WriteTo.AndroidLog()
                .CreateLogger();`

When the parameter "shared" is set to true, no file is created. When set to false it correctly creates the file. I'm not sure if this is a bug or if I'm misunderstanding how the shared property works :)

**Comment by nblumhardt** [comment] 2017-12-04 03:22
Hi! To be honest, I didn't realize that this package even runs under Xamarin :-) ... I'd guess it's a platform limitation, but couldn't pinpoint it without some digging around. @geoffreyhuntley may have encountered this somewhere.

**Comment by helsq** [comment] 2018-01-11 01:14
Hi, there! 
I have same problem in Xamarin.iOS.
Yes, if you set the parameter "shared" to true then log file isn't created. Because file sink use named mutex for synchronization. Named mutex isn't supported on mobile platforms. 
`Caught exception while emitting to sink Serilog.Sinks.File.RollingFileSink: System.NotSupportedException: Specified method is not supported.
  at System.Threading.Mutex..ctor (System.Boolean initiallyOwned, System.String name) [0x00006] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.3/src/mono/mcs/class/corlib/System.Threading/Mutex.cs:167`

**Comment by CostaTC** [comment] 2018-01-11 03:25
Thanks for the info @helsq!

I suppose this means this isn't resolvable - or, at least, not really an issue for this library? 
Pity, as file sharing has been a bit of a nightmare to deal with!

**Comment by helsq** [comment] 2018-01-11 05:00
I think that this isn't resolvable if won't change method of processors synchronization.

**Comment by nblumhardt** [comment] 2018-05-02 21:41
I think it's superficially resolvable - we could not synchronize access to the shared file for Xamarin, but then the file might show garbled/interleaved/corrupted data if multiple processes write to it concurrently. May be a fair trade-off to explore, if anyone's interested in putting together a proposal/PR. Cheers!

**Comment by nblumhardt** [comment] 2018-05-18 21:12
Closing while we don't have any action items on this, but please feel free to jump in if you're keen to dig in deeper.

**Closed by nblumhardt** 2018-05-18 21:12 UTC

**Comment by kyurkchyan** [comment] 2019-08-12 12:25
Came across this issue while investigating another one   #109

**Comment by salamoun** [comment] 2019-08-26 15:46
I can confirm that shared flag DOES NOT work on Xamarin.iOS/Android even when serilog is only process that is accessing file.
Setting shared to true and no file is created.
I think that is some problem on Xamarin platform. On .NET Standard project on Windows, shared flag works as expected.

**Comment by nblumhardt** [comment] 2019-08-27 06:12
@salamoun thanks for jumping in!

As far as I know, no one maintaining this project currently uses Xamarin, so we're not able to make progress on this without some help.

Collecting `SelfLog` output to see whether `shared: true` generates an exceptions, and raising a new ticket with the exception message/stack trace, would be a great help if you (or anyone else watching this ticket) have a chance to investigate further. Thanks!

**Comment by Wolfteam** [comment] 2019-11-26 02:39
Hi, sorry to revive this one, but what about just using the mutex ctor without providing a name in case of a not supported ex?
````
In the SharedFileSink ctor
            try
            {
                _mutex = new Mutex(false, mutexName);
            }
            catch (Exception)
            {
                _mutex = new Mutex(false);
            }
````

**Comment by nblumhardt** [comment] 2019-11-26 04:06
@Wolfteam thanks for the suggestion; the semantics of the two constructors are very different, one is interprocess, the other isn't. Cheers!

**Comment by cesar-moya** [comment] 2019-12-06 03:12
Hi guys,

I'm interested on using this sink on Xamarin forms but I'm also encountering the same issue when setting the shared flag. Is there any work ongoing to allow supporting Xamarin? Thanks!

**Comment by nblumhardt** [comment] 2019-12-06 03:16
Hi @cesar-moya - no, no one is actively working on this as far as I know, though there is work ongoing in https://github.com/serilog/serilog-sinks-xamarin. Any help/investigation here would be welcome. Cheers!

**Comment by cesar-moya** [comment] 2019-12-06 03:27
> Hi @cesar-moya - no, no one is actively working on this as far as I know, though there is work ongoing in https://github.com/serilog/serilog-sinks-xamarin. Any help/investigation here would be welcome. Cheers!

Hi @nblumhardt, thanks for your quick reply. I implemented it as-is (without the shared flag) and it seems to be working fine. I am logging from multiple background threads, Do you know if it could cause unexpected application behavior or crashes if i continue to use it in this manner? Thanks!

**Comment by nblumhardt** [comment] 2019-12-06 04:33
Sounds like you have a single application process running; if so, this will work fine, @cesar-moya 👍

**Comment by cesar-moya** [comment] 2019-12-06 04:46
@nblumhardt Yes as far as I understand, since this is a mobile application it runs on a single application process, but inside of it creates multiple background (and foreground) threads, all of which write to the log. I will report any errors if i see them. Thanks!
