### ISSUE TITLE
Support for rotation of audit logs

### ISSUE THREAD

**Issue by goodrod** [serilog/serilog-sinks-file#314] opened 2024-07-04 09:06 UTC
**Is your feature request related to a problem? Please describe.**
We would like to be able to rotate audit logs, but are unable since (as far as I understand) Serilog.Sinks.File does not support:
1. Built in rotation of audit logs.
2. Recreation of logs if deleted.

**Describe the solution you'd like**
Ideally built in support for audit logs, just like for normal logs. Or the ability to recreate deleted logs so that we can rotate them by other means.

**Describe alternatives you've considered**
We have considered:
- Truncating all of the content after rotation, but risk losing audit logs (which is not acceptable)
- Truncating part of the content (i.e. up til 1 hour old events), but this is not acceptable for our customer (the export will contain duplicate logs)

**Comment by nblumhardt** [comment] 2024-07-04 23:30
Duplicate of #113, where some workarounds are discussed. Help appreciated if anyone's able to put a PR together. https://github.com/serilog/serilog-sinks-file/issues/113#issuecomment-2084619061

**Closed by nblumhardt** 2024-07-04 23:30 UTC
Labels: enhancement
