### ISSUE TITLE
AuditTo RollingFile does not seem to be supported

### ISSUE THREAD

**Issue by dbones** [serilog/serilog-sinks-file#175] opened 2020-08-17 12:15 UTC
Hi

Im using
- Serilog - 2.9.0
- Serlog.Sinks.File - 4.1.0

I am trying to do the following

```
auditLogger  = new LoggerConfiguration()
                .AuditTo.File(new JsonFormatter(),"audit.txt", rollingInterval: RollingInterval.Hour)
                .CreateLogger();
```
however the `AuditTo.File()` does not seem to have the same API as the `WriteTo.File`

How can we set up a rolling file with AuditTo?

**Comment by nblumhardt** [comment] 2020-08-18 04:45
Hi! Thanks for getting in touch. This is a duplicate of #113 - thanks!

**Closed by nblumhardt** 2020-08-18 04:45 UTC
Labels: duplicate
