### ISSUE TITLE
I want my Log file name in the format "D:\Log\FileName-{Date}-INew.txt"

### ISSUE THREAD

**Issue by amande4x** [serilog/serilog-sinks-file#298] opened 2023-10-13 22:54 UTC
I want my generated text file name of format. "D:\Log\FileName-{Date}-INew.txt"
Currently its appending Date towards the end of the file,
"D:\Log\FileName-INew-20231010.txt"
Expected
"D:\Log\FileName-20231010-INew.txt"

                .WriteTo.Logger(l =>
                {
                    l.WriteTo.File(
                            config.GetValue<string>(GenericConstants.TentFilePathKey)!,
                            rollingInterval: RollingInterval.Day,
                            retainedFileCountLimit: null,
                            outputTemplate: GenericConstants.LogOutputTemplateToken
                    );
                    l.Filter.ByIncludingOnly(e => e.Properties.ContainsKey(GenericConstants.NewFile));
                });

**Comment by bartelink** [comment] 2023-10-14 06:25
Duplicate of #243 - the logic for generating filenames is definitely minimal in nature.

Solving that would involve:
- defining the possibilities to provide
- defining a clear API/mechanism for specifying it
- correlating the feature request with the current implementation to make sure it's implementable
- implementing it

**Comment by bartelink** [comment] 2023-10-19 08:05
Had left this open in case you wanted to respond; assuming the above covers it

**Closed by bartelink** 2023-10-19 08:05 UTC
Labels: enhancement
