### ISSUE TITLE
Rolling file throws exception with Windows 10 IoT

### ISSUE THREAD

**Issue by NorthPoleDemo** [serilog/serilog-sinks-file#117] opened 2019-10-24 14:37 UTC
The exception is in a UWP application with Serilog 2.9.0 and Serilog.Sinks.File v4.1.0 and it only fails on Windows 10 IoT (on ARM  Raspberry Pi). The same code on Windows 10 desktop x86 runs correctly. The error is 100% reproducible.

If rollingInterval is set or rollOnFileSize is true, Log.Information throws an exception:
`Caught exception while emitting to sink Serilog.Sinks.File.RollingFileSink: System.IO.IOException: Invalid access to memory location`

The memory location shown is the location of the log file. If I do not enable rollingInterval, then it logs correctly, but of course the log files will grow indefinitely.

Complete stack trace follows:

`2019-10-24T14:29:43.7628576Z Caught exception while emitting to sink Serilog.Sinks.File.RollingFileSink: System.IO.IOException: Invalid access to memory location : '...filename redacted...'
   at System.IO.Enumeration.FileSystemEnumerator"1.FindNextEntry()
   at System.IO.Enumeration.FileSystemEnumerator"1.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder"1.AddRange(IEnumerable"1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable"1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable"1 source)
   at Serilog.Sinks.File.RollingFileSink.OpenFile(DateTime now, Nullable"1 minSequence)
   at Serilog.Sinks.File.RollingFileSink.AlignCurrentFileTo(DateTime now, Boolean nextSequence)
   at Serilog.Sinks.File.RollingFileSink.Emit(LogEvent logEvent)
   at Serilog.Core.Sinks.SafeAggregateSink.Emit(LogEvent logEvent)`

**Comment by nblumhardt** [comment] 2019-10-25 01:37
Hi! Thanks for the note. I think we're using very vanilla filesystem APIs here - the enumerator that's throwing is the return value of `Directory.GetFiles()`:

https://github.com/serilog/serilog-sinks-file/blob/5b52dd29f0547b2c5a11caa4f6488d9de6d77683/src/Serilog.Sinks.File/Sinks/File/RollingFileSink.cs#L123

The issue is more than likely a BCL issue on the target platform; the [dotnet/corefx](https://github.com/dotnet/corefx) repository is the place to start, I think.

**Comment by magnus-andersen** [comment] 2020-01-10 17:26
I'm getting the same exception on Windows IoT Core (ARM32). It works if I turn off rolling.

**Comment by nblumhardt** [comment] 2020-01-10 21:32
Thanks for the note, @magnus-andersen.

I don't think this is a Serilog-specific issue (or one we can address directly), so I'll close this ticket, but it would be great if anyone is able to get down to the root cause and report some findings! Cheers!

**Closed by nblumhardt** 2020-01-10 21:32 UTC
