### ISSUE TITLE
fileSizeLimitBytes and rollOnFileSizeLimit rolling file name problem

### ISSUE THREAD

**Issue by lucalas** [serilog/serilog-sinks-file#217] opened 2021-05-17 21:39 UTC
Hi, I'm using your library and try to implement rolling policy based on file size limit.
I have my log file named log.txt, when file size limit event is fired the old log remain log.txt and new log "log_001.txt" is created.

I think that the correct behaviour should be:
when file size limit event fired the old log rename to log_001.txt and new log appears as log.txt

My configuration  is:
``` C#
Log.Logger = new LoggerConfiguration()
                .WriteTo.Console(outputTemplate: logTemplate)
                .WriteTo.File("log.txt", rollOnFileSizeLimit: true, fileSizeLimitBytes: fileSizeLimit, outputTemplate: logTemplate)
                .CreateLogger();
```

What do you think?

**Comment by cocowalla** [comment] 2021-05-18 09:05
Hi, thanks for asking! I think this is a duplicate of #40

**Closed by cocowalla** 2021-05-18 09:05 UTC
