### ISSUE TITLE
UWP app sometimes does not generate files

### ISSUE THREAD

**Issue by alexiordan** [serilog/serilog-sinks-file#101] opened 2019-05-12 21:07 UTC
I use serilog for an UWP app. It is a Background Task app running on Windows 10 IoT Core. Sometimes my serilog files doesn't get generated. My app seems to be running well.
What can I do to see why is this happening so to be able to fix it?

**Comment by nblumhardt** [comment] 2019-05-24 03:58
Hi @alexiordan - you can use `SelfLog.Enable(message => /* display message somewhere */)` to get diagnostics out of Serilog at runtime. Check out: https://github.com/serilog/serilog-sinks-file/wiki for more info.

Chances are, the diagnostics will explain this behavior, so I'll close this for now. Please get in touch if the info from `SelfLog` is not adequate. Thanks!

**Closed** 2019-05-24 03:58 UTC

**Comment by magnus-andersen** [comment] 2019-10-03 09:48
I'm having the same problem (UWP, Background Task app on IoT Core) but only in release mode, not debug. The log files are created in the so-called publisher cache folder (which the app has full write-access to), but log files are almost never generated (except once in a blue moon they are).

**Comment by alexiordan** [comment] 2020-05-21 05:54
Any updates on this? @nblumhardt  is there any fix to @magnus-andersen reported issue?

**Comment by nblumhardt** [comment] 2020-05-22 00:33
@alexiordan Hi! Did you collect `SelfLog` output? A fix will only be possible with more diagnostic information that confirms _Serilog.Sinks.File_ is the problem.

UWP is quirky, and I don't target it in any of my own projects, so the chances of me spotting the cause are slim. Happy to help if someone does the leg work to narrow down the cause, though, sorry.

**Comment by alexiordan** [comment] 2021-03-04 15:53
Hi @nblumhardt ,
Sorry for this long delay, but got the chance to check what you instructed me to.

Running in Release mode I get the exception below (with SelfLog enabled).
I've seen this stackoverflow question https://stackoverflow.com/questions/38559390/uwp-run-in-release-mode-gives-applicationdata-does-not-exist-in-the-current-c , but I am not using neither .Net Native tool chain nor code optimization.
The folder exists, since I have other files there used for database for instance.

If you think that some Serilog initialisation occurs to early in Release mode, is there any option to initialize it a little bit later (when maybe the folders are created)

2021-03-04T15:26:21.4648420Z Caught exception while emitting to sink Serilog.Sinks.File.PeriodicFlushToDiskSink: System.IO.IOException: Invalid access to memory location : 'C:\Data\Users\DefaultAccount\AppData\Local\Packages\[app-id]\LocalState'
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry()
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Serilog.Sinks.File.RollingFileSink.OpenFile(DateTime now, Nullable`1 minSequence)
   at Serilog.Sinks.File.RollingFileSink.AlignCurrentFileTo(DateTime now, Boolean nextSequence)
   at Serilog.Sinks.File.RollingFileSink.Emit(LogEvent logEvent)
   at Serilog.Sinks.File.PeriodicFlushToDiskSink.Emit(LogEvent logEvent)
   at Serilog.Core.Sinks.SafeAggregateSink.Emit(LogEvent logEvent)

**Comment by alexiordan** [comment] 2021-03-04 16:20
@magnus-andersen , further googling I ran into this issue here: https://github.com/dotnet/runtime/issues/27943
I have updated the Microsoft.NETCore.UniversalWindowsPlatform nugetpackage to 6.2.12 (from 6.2.8) and seems to work now.

So @nblumhardt , this remains closed since it seems not to be serilog's issue.
