### ISSUE TITLE
File name format

### ISSUE THREAD

**Issue by AlexaCodex** [serilog/serilog-sinks-file#85] opened 2019-02-26 15:58 UTC
For rolling file format, Log4Net follows something like this convention:
1) Active/Current file to which log are written - degub.txt etc
2) Old file where log are not getting written to : degub-{date}.txt

Is it possible to achieve this in Serilog? We want log files to roll but want the active/current file not to have any date in it's file name i.e. degub.txt

Thanks

**Comment by AlexaCodex** [comment] 2019-03-08 16:29
@nblumhardt ??

**Comment by nblumhardt** [comment] 2019-03-08 21:43
Hi @AlexaCodex - sorry about the delay. This one is a duplicate of #40.

**Closed by nblumhardt** 2019-03-08 21:43 UTC
Labels: duplicate
