### ISSUE TITLE
Customize filename to remove date

### ISSUE THREAD

**Issue by osnipezzini** [serilog/serilog-sinks-file#259] opened 2022-06-30 16:28 UTC
It would be interesting to have some way of using the same file name that we informed in the configuration, and that only the previous log would be backed up using the timestamp. The most correct still, would be a folder where I saved the previous logs to be more organized.

**Comment by nblumhardt** [comment] 2022-06-30 22:37
Duplicate of #243

**Closed by nblumhardt** 2022-06-30 22:37 UTC
Labels: duplicate
