### ISSUE TITLE
How can I get the log file directory at runtime?

### ISSUE THREAD

**Issue by chucklu** [serilog/serilog-sinks-file#170] opened 2020-07-29 06:36 UTC
```  C#
 loggerConfiguration = loggerConfiguration.ReadFrom.AppSettings(filePath: path);
                    var logger = loggerConfiguration.CreateLogger();
                    Log.Logger = logger;
```
After create the logger, I would like to get the log file directory from the logger. However, I checked the source code, find you encapsulate class with lots of private fields and initialize fields with constructor.
Then how could I get the [LogFileDirectoy](https://github.com/serilog/serilog-sinks-file/blob/dev/src/Serilog.Sinks.File/Sinks/File/PathRoller.cs#L61) at runtime?
The [PathRoller instance](https://github.com/serilog/serilog-sinks-file/blob/dev/src/Serilog.Sinks.File/Sinks/File/RollingFileSink.cs#L28) is a private field of RollingFileSink.

**Comment by chucklu** [comment] 2020-07-29 06:42
I can check the log file directory through watch window when debug program. However the access route are all private fields.
It's weird design for me, could you told me why you did not consider to sue public property?
![image](https://user-images.githubusercontent.com/3004057/88765499-2a71ca00-d1a9-11ea-94a2-ef37a415e713.png)

**Comment by nblumhardt** [comment] 2020-07-29 08:39
Hi! This one's a duplicate of #154

**Closed by nblumhardt** 2020-07-29 08:39 UTC
