### ISSUE TITLE
How Can I Avoid Appending Date Until After File Roll

### ISSUE THREAD

**Issue by jrichardsz** [serilog/serilog-sinks-file#251] opened 2022-03-18 19:43 UTC
I wonder if using some configuration we can avoid the date on the filename for the current day. Change to file size rolling is not an option for me.

In the previous version **Serilog.Sinks.RollingFile** my logs were for the default configuration
```
var log = new LoggerConfiguration()
    .WriteTo.File("log.txt", rollingInterval: RollingInterval.Day)
    .CreateLogger();
```
```
- log.txt
- log20180702.txt
- log20180703.txt
```

With that It was easy to read the current log by another process because always was **log.txt** . But using the same configuration but with **Serilog.Sinks.File - 5.0.0** the logs are

```
log20180701.txt
log20180702.txt
log20180703.txt
```

Related issues:

- https://github.com/serilog/serilog-sinks-rollingfile/issues/78

Thanks

**Comment by cocowalla** [comment] 2022-03-18 21:01
Duplicate of https://github.com/serilog/serilog-sinks-file/issues/40 - see https://github.com/dfacto-lab/serilog-sinks-file for an impl of what you are after

**Closed by cocowalla** 2022-03-18 21:01 UTC
