### ISSUE TITLE
Have RollingFile sink support a Reverse Roll-down instead of a RollUp

### ISSUE THREAD

**Issue by EdLichtman** [serilog/serilog-sinks-file#321] opened 2024-09-16 14:26 UTC
**Is your feature request related to a problem? Please describe.**
Our current log4net implementation creates logfiles with:
File.log
File.1.log
File.2.log

Where File.2.log is the oldest.

Right now, the only way to log files is either by date, with shared, or every single time I start up the application, it seems to create a new file, File_X.txt

Also, I noticed that if I give it a rollingInterval of "Day", and I append "-", then the file is File-X.txt. But when I do NOT have a rollingInterval, and I attempt to give it a path separator (.) then the first file shows up as File..txt.

Therefore, it would be nice to have a configuration to make it easy to implement some sort of file increment separator.

This would only be a nice to have. The property decrease is far more important of a need to me.

**Describe the solution you'd like**
I'd like a new property, or two:
1) rollingType: increase (default) | decrease
  * I'm open to alternative variable names and descriptors. I just wanted to give the idea of an enum type for how to roll
2) rollingIncrementSeparator (defaults to "_")
  * This way, we don't have to "know the ins and outs of Serilog Path Templating", and we can be strict about how we want the path incremented.

**Describe alternatives you've considered**
I'm open to creating my own Sink, and for the time being, I'm planning to. However, I personally think that for other organizations that have log4net and are trying to transition over to using smarter logging features, it would be a VERY good idea to implement replicating logic. We aren't doing custom Log4net appending to perform a rolldown. This is our Log4Net configuration:

```xml
  <appender name="SupportFileLog" type="log4net.Appender.RollingFileAppender">
    <file value="$(PathToLogs)\\File.log"/>
    <appendToFile value="true"/>
    <rollingStyle value="Size"/>
    <maxSizeRollBackups value="8"/>
    <maximumFileSize value="5MB"/>
    <staticLogFileName value="true"/>
    <encoding value="utf-8"/>
    <layout type="log4net.Layout.PatternLayout">
      <conversionPattern value="%date %9timestamp %-6level %-15.15thread %message [%ndc] %logger%n"/>
    </layout>
    <filter type="log4net.Filter.LevelRangeFilter">
      <param name="LevelMin" value="DEBUG"/>
      <param name="LevelMax" value="FATAL"/>
    </filter>
  </appender>
```

If you approve of this issue, I'll see about forking this and working on it to match the code styles that you guys have set out for yourselves, but until then I need to fit it into our code-base. Please let me know!

**Comment by bartelink** [comment] 2024-09-17 15:35
Duplicate of #40 (Feel free to re-open if I'm wrong)

**Closed by bartelink** 2024-09-17 15:35 UTC
Labels: enhancement
