### ISSUE TITLE
Log file rotation

### ISSUE THREAD

**Issue by ThangHuuVu** [serilog/serilog-sinks-file#60] opened 2018-07-12 03:10 UTC
Is it configurable to always write logs to 1 specific file, and truncate it when it reaches file size limit? 
I want to achieve something like:
Mainlog.log: The log file that will always be written to. It contains the latest log.
Log_001.log -> Log_009.log: The archived log files.

**Comment by nblumhardt** [comment] 2018-09-21 23:45
Hi - I think this is a duplicate of #40 - thanks!

**Closed by nblumhardt** 2018-09-21 23:45 UTC
